dependencies:
  - OpenZeppelin/openzeppelin-contracts-upgradeable@3.3.0

compiler:
  solc:
    version: 0.6.12
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts-upgradeable@3.3.0"
